package com.hospital.enums;

public enum ETypeHospital {

    GYNECOLOGY,
    PEDIATRIE,
    OPHTAMOLOGIE,
    RADIOLOGIE,
    ODONOSTOMATOLOGIE,
    CARDIOLOGIE,
    PSHYCOLOGIE,
    MEDECINE_GENERALE,
    IMMUNOLOGIE,
    CHIRUGIE,
    NEUROLOGIE,
    PNEUMOLOGIE,
    ODONTOLOGIE,
    DERMATOLOGIE,
    SERVICE_ACCUEIL_TRAITEMENT_URGENCE,
    TRAUMATOLOGIE,
    MEDECINE_INTERNE,
    ENDOCRINOLOGIE,
    ANATOMO_PATHOLOGIE,
    HEMATOLOGIE,
    GASTRO_ENTEROLOGIE,
    UROLOGIE,
    MATERNITE,
    PHARMACIE,
    LABORATOIRES

}
